<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<c:if test="${sessionScope.locale != null}">
    <fmt:setLocale value="${sessionScope.locale}"/>
</c:if>
<fmt:setBundle basename="appLocalization"/>

<fmt:message key="title" var="title"/>
<fmt:message key="manager" var="manager"/>
<fmt:message key="menu" var="menu"/>
<fmt:message key="manager_page" var="manager_page"/>
<fmt:message key="about" var="about"/>
<fmt:message key="delivery" var="delivery"/>
<fmt:message key="support" var="support"/>
<fmt:message key="basket" var="basket"/>
<fmt:message key="account" var="account"/>
<fmt:message key="account.logged" var="account_logged"/>
<fmt:message key="account.not_logged" var="account_not_logged"/>
<fmt:message key="account.sign_in" var="account_sign_in"/>
<fmt:message key="account.sign_out" var="account_sign_out"/>
<fmt:message key="welcome" var="welcome"/>
<fmt:message key="language" var="language"/>
<fmt:message key="english" var="english"/>
<fmt:message key="russian" var="russian"/>
<fmt:message key="account.your_account" var="account_your_account"/>
<fmt:message key="account.personal_information" var="account_personal_information"/>
<fmt:message key="email" var="email"/>
<fmt:message key="phone" var="phone"/>
<fmt:message key="account.orders" var="account_orders"/>
<fmt:message key="account.orders_empty" var="account_orders_empty"/>
<fmt:message key="order_number" var="order_number"/>
<fmt:message key="status" var="order_status"/>
<fmt:message key="order_information" var="order_information"/>
<fmt:message key="date_time" var="date_time"/>
<fmt:message key="cost" var="cost"/>
<fmt:message key="address" var="address"/>
<fmt:message key="payment" var="payment"/>
<fmt:message key="orders" var="orders"/>
<fmt:message key="sort" var="sort"/>
<fmt:message key="sort.default" var="sort_default"/>
<fmt:message key="sort.users" var="sort_users"/>
<fmt:message key="sort.status" var="sort_status"/>
<fmt:message key="sort.date" var="sort_date"/>
<fmt:message key="sort.date_desc" var="sort_date_desc"/>
<fmt:message key="filter_by_status" var="filter_by_status"/>
<fmt:message key="any_status" var="any_status"/>
<fmt:message key="accepted" var="accepted"/>
<fmt:message key="confirmed" var="confirmed"/>
<fmt:message key="preparing" var="preparing"/>
<fmt:message key="delivering" var="delivering"/>
<fmt:message key="completed" var="completed"/>
<fmt:message key="rejected" var="rejected"/>
<fmt:message key="uncompleted" var="uncompleted"/>
<fmt:message key="order" var="_order"/>
<fmt:message key="user" var="_user"/>
<fmt:message key="status" var="status"/>
<fmt:message key="change_status" var="change_status"/>
<fmt:message key="previous" var="previous"/>
<fmt:message key="next" var="next"/>
<fmt:message key="cart" var="cart"/>
<fmt:message key="cart_empty" var="cart_empty"/>
<fmt:message key="product" var="product"/>
<fmt:message key="quantity" var="quantity"/>
<fmt:message key="price" var="price"/>
<fmt:message key="price_total" var="price_total"/>
<fmt:message key="uah" var="uah"/>
<fmt:message key="remove" var="remove"/>
<fmt:message key="free" var="free"/>
<fmt:message key="total" var="total"/>
<fmt:message key="make_purchase" var="make_purchase"/>
<fmt:message key="continue_shopping" var="continue_shopping"/>
<fmt:message key="email_confirm" var="email_confirm"/>
<fmt:message key="email_confirm.success" var="email_confirm_success"/>
<fmt:message key="email_confirm.success" var="email_confirm_success"/>
<fmt:message key="email_confirm.success_info" var="email_confirm_success_info"/>
<fmt:message key="email_confirm.error" var="email_confirm_error"/>
<fmt:message key="email_confirm.error_info" var="email_confirm_error_info"/>
<fmt:message key="delivery.info" var="delivery_info"/>
<fmt:message key="delivery.city" var="delivery_city"/>
<fmt:message key="delivery.less_min_sum" var="delivery_less_min_sum"/>
<fmt:message key="delivery.region" var="delivery_region"/>
<fmt:message key="our_menu" var="our_menu"/>
<fmt:message key="sort.popularity" var="sort_popularity"/>
<fmt:message key="sort.category" var="sort_category"/>
<fmt:message key="sort.price" var="sort_price"/>
<fmt:message key="sort.price_desc" var="sort_price_desc"/>
<fmt:message key="sort.name" var="sort_name"/>
<fmt:message key="categories" var="categories"/>
<fmt:message key="all_products" var="all_products"/>
<fmt:message key="pizza" var="pizza"/>
<fmt:message key="sushi" var="sushi"/>
<fmt:message key="salad" var="salad"/>
<fmt:message key="pasta" var="pasta"/>
<fmt:message key="dessert" var="dessert"/>
<fmt:message key="drinks" var="drinks"/>
<fmt:message key="volume" var="volume"/>
<fmt:message key="weight" var="weight"/>
<fmt:message key="l" var="l"/>
<fmt:message key="g" var="g"/>
<fmt:message key="add_to_basket" var="add_to_basket"/>
<fmt:message key="login" var="login"/>
<fmt:message key="login.info" var="login_info"/>
<fmt:message key="login.sign_in" var="login_sign_in"/>
<fmt:message key="login.create_account" var="login_create_account"/>
<fmt:message key="login.sign_up" var="login_sign_up"/>
<fmt:message key="welcome_back" var="welcome_back"/>
<fmt:message key="welcome_back.info" var="welcome_back_info"/>
<fmt:message key="hello_friend" var="hello_friend"/>
<fmt:message key="hello_friend.info" var="hello_friend_info"/>
<fmt:message key="verify_email" var="verify_email"/>
<fmt:message key="order_details" var="order_details"/>
<fmt:message key="checkout" var="checkout"/>
<fmt:message key="details" var="details"/>
<fmt:message key="payment.select_payment_type" var="payment_select_payment_type"/>
<fmt:message key="cash" var="cash"/>
<fmt:message key="card_online" var="card_online"/>
<fmt:message key="card_offline" var="card_offline"/>
<fmt:message key="cancel" var="cancel"/>
<fmt:message key="proceed" var="proceed"/>
<fmt:message key="payment_details" var="payment_details"/>
<fmt:message key="card_number" var="card_number"/>
<fmt:message key="card_holders_name" var="card_holders_name"/>
<fmt:message key="card_expiration_date" var="card_expiration_date"/>
<fmt:message key="order_confirmed" var="order_confirmed"/>
<fmt:message key="thanks_for_order" var="thanks_for_order"/>
<fmt:message key="delivery_details" var="delivery_details"/>
<fmt:message key="payment.payment" var="payment_payment"/>
<fmt:message key="support_page" var="support_page"/>
<fmt:message key="password" var="password"/>
<fmt:message key="name" var="name"/>